name: PR Check

on:
  pull_request:
    branches:
      - main

jobs:
  pr-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18.18.2

      - name: Get yarn cache directory path 🛠
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT

      - name: Cache node_modules 📦
        uses: actions/cache@v3
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Set Env values
        run: |
          echo "RESAS_API_KEY=${{ secrets.RESAS_API_KEY }}" >> "$GITHUB_ENV"
          echo "BASE_URL=${{ secrets.BASE_URL }}" >> "$GITHUB_ENV"

      - name: Install packages
        run: yarn

      - name: ESLint Check
        run: yarn eslint:check

      - name: Stylelint Check
        run: yarn stylelint:check

      - name: Prettier Check
        run: yarn prettier:check

      - name: Jest Check
        run: yarn test:check

      - name: Build Check
        run: yarn build
